# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - cn1-p1-lieberte-webapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install, build, and test
        run: |
          npm install
          # Note: 'npm run build' and 'npm run test' são ignorados neste projeto simples
          
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    # Permissões de ID Token não são mais necessárias com o publish-profile
    permissions:
      contents: read 

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
          
      # REMOVIDA: Etapa de Login do Azure usando OIDC
      
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'cn1-p1-lieberte-webapp'
          slot-name: 'Production'
          package: .
          # USANDO O PROFILE DE PUBLICAÇÃO PARA AUTENTICAÇÃO
          # Você deve criar um SECRET no GitHub chamado AZURE_WEBAPP_PUBLISH_PROFILE
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }} 

